package:
  name: '{{ PACKAGE_NAME }}'
  version: '{{ PACKAGE_VERSION }}'
source:
  path: ../src
requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - transforms {{ PYTHON_TRANSFORMS_VERSION }}
  - transforms-expectations
  - transforms-preview
  - transforms-verbs
  - foundry-transforms-lib-python
  - numpy
  - ccda-omop-conversion-package 2.19.0
  pip:
  - pandas
  - typeguard
  - lxml
  - duckdb
test:
  requires:
    - ccda-omop-conversion-package 2.19.0
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
 